import type { Service } from '@/lib/content/types'

/**
 * Services/Classes - JSON source
 * Extracted from PowerFlow HTML template
 */
export const servicesData: Service[] = [
  {
    id: 'strength-conditioning',
    name: 'Strength & Conditioning',
    slug: 'strength-conditioning',
    description: 'Build lean muscle and boost endurance with structured weightlifting and functional training designed for all fitness levels.',
    shortDescription: 'Build muscle and endurance with structured training.',
    image: '/images/classes/1.webp',
    duration: 60,
    intensity: 'High',
    maxParticipants: 15,
    benefits: ['Increases strength', 'Builds muscle', 'Improves endurance'],
    featured: true,
    order: 1,
  },
  {
    id: 'hiit-training',
    name: 'HIIT Training',
    slug: 'hiit-training',
    description: 'High-intensity interval training that maximizes calorie burn, improves cardiovascular fitness, and delivers results in less time.',
    shortDescription: 'Maximize calorie burn with high-intensity intervals.',
    image: '/images/classes/2.webp',
    duration: 45,
    intensity: 'High',
    maxParticipants: 20,
    benefits: ['Burns calories fast', 'Boosts metabolism', 'Improves cardio'],
    featured: true,
    order: 2,
  },
  {
    id: 'yoga-flexibility',
    name: 'Yoga & Flexibility',
    slug: 'yoga-flexibility',
    description: 'Enhance flexibility, balance, and mindfulness through guided yoga flows suitable for beginners and advanced practitioners alike.',
    shortDescription: 'Enhance flexibility and mindfulness through yoga.',
    image: '/images/classes/3.webp',
    duration: 60,
    intensity: 'Low',
    maxParticipants: 25,
    benefits: ['Improves flexibility', 'Reduces stress', 'Enhances balance'],
    featured: false,
    order: 3,
  },
  {
    id: 'spinning-cycle',
    name: 'Spinning & Cycle',
    slug: 'spinning-cycle',
    description: 'Indoor cycling classes that push your limits with energizing music, motivating instructors, and community energy.',
    shortDescription: 'Indoor cycling with energizing music and motivation.',
    image: '/images/classes/4.webp',
    duration: 45,
    intensity: 'Medium',
    maxParticipants: 30,
    benefits: ['Cardio endurance', 'Lower body strength', 'Group motivation'],
    featured: false,
    order: 4,
  },
  {
    id: 'boxing-martial-arts',
    name: 'Boxing & Martial Arts',
    slug: 'boxing-martial-arts',
    description: 'Develop power, speed, and confidence through boxing drills and martial arts techniques in a safe, supportive environment.',
    shortDescription: 'Develop power and confidence through martial arts.',
    image: '/images/classes/5.webp',
    duration: 60,
    intensity: 'High',
    maxParticipants: 12,
    benefits: ['Builds power', 'Improves coordination', 'Stress relief'],
    featured: false,
    order: 5,
  },
  {
    id: 'pilates-core',
    name: 'Pilates & Core',
    slug: 'pilates-core',
    description: 'Strengthen your core, improve posture, and increase flexibility with low-impact Pilates movements.',
    shortDescription: 'Strengthen core and improve posture with Pilates.',
    image: '/images/classes/6.webp',
    duration: 50,
    intensity: 'Medium',
    maxParticipants: 18,
    benefits: ['Core strength', 'Better posture', 'Flexibility'],
    featured: false,
    order: 6,
  },
  {
    id: 'zumba-dance',
    name: 'Zumba & Dance Fitness',
    slug: 'zumba-dance',
    description: 'Dance your way to fitness with high-energy Zumba classes that combine cardio, coordination, and fun.',
    shortDescription: 'Dance fitness with high-energy cardio.',
    image: '/images/classes/7.webp',
    duration: 55,
    intensity: 'Medium',
    maxParticipants: 25,
    benefits: ['Fun cardio', 'Coordination', 'Full body workout'],
    featured: false,
    order: 7,
  },
  {
    id: 'personal-training',
    name: 'Personal Training',
    slug: 'personal-training',
    description: 'One-on-one coaching tailored to your specific goals, fitness level, and schedule with our certified trainers.',
    shortDescription: 'One-on-one coaching tailored to your goals.',
    image: '/images/classes/8.webp',
    duration: 60,
    intensity: 'High',
    maxParticipants: 1,
    benefits: ['Customized program', 'Personal attention', 'Faster results'],
    featured: true,
    order: 8,
  },
]
